apiVersion: apps/v1
kind: Deployment
metadata:
  name: doubler-service-deployment
  labels:
    app: adder-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doubler-service
  template:
    metadata:
      labels:
        app: doubler-service
    spec:
      containers:
      - name: adder-service
        image: rparitosh/doubler-service:LATEST
        imagePullPolicy: Always
        ports:
          - containerPort: 9002
---

apiVersion: v1
kind: Service
metadata:
  name: doubler-service
spec:
  selector:
    app: doubler-service
  ports:
  - port: 9002
    targetPort: 9002
  type: NodePort

          
    
    

